/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algo3;

import Algo3.commands.StackCommand;
import Algo3.data.Student;
import Algo3.stacks.Stack;
import Algo3.stacks.Stackable;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        new StackCommand().execute();
    }
}
